name: master-cache.yml
on:
  pull_request:
    types: [ closed ]
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:

  create-master-cache:
    name: Compile & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          toolchain: stable

      - name: Build Crate
        run: cargo build

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.0

